project:
  type: website
  output-dir: .

website:
  title: "Jarrod Zammit"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: cv.qmd
        text: "CV"
        
format:
  html:
    theme:
      - flatly
    css: styles.css
    toc: true