project:
  type: website
  output-dir: .

website:
  title: "Jarrod Zammit"
  navbar:
    left:
      - href: index.qmd
        text: "Home"
      - href: academic-history.qmd
        text: "History & CV"
        

format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true